vich_uploader:
    db_driver: orm
    
    mappings:
        property_images:
            uri_prefix: '/image/books'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/image/books'